rules:
  - id: no-eval-exec
    pattern-either:
      - pattern: eval(...)
      - pattern: exec(...)
    message: "El uso de eval() o exec() es peligroso y puede permitir la ejecucion arbitraria de codigo. Evitalo."
    severity: ERROR
    languages: [python]
